---
title: Eren Taşçı
timezone: Europe/Istanbul
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Eren Taşçı
description: Software Development & Cyber Security
avatar: "/uploads/IMG_3351-1.jpg"
footer-links:
  dribbble: 
  email: erent4sci@gmail.com
  facebook: 
  flickr: 
  github: erentasci
  instagram: er3ntasci
  linkedin: 
  pinterest: 
  rss: 
  twitter: er3ntasci
  stackoverflow: 
  youtube: 
  googleplus: 
disqus: 
google_analytics: 
url: 
baseurl: 
permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: expanded
gems:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
